<?php

namespace Database\Seeders;

use App\Models\siswa;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class XII_PH_1 extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $kelas = [
            [
                'nisn' => 123123123,
                'nama' => 'Agil Sulthon Mansyur',
                'nama_kelas_id' => 3,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
            [
                'nisn' => 123123123,
                'nama' => 'Agus Saputra',
                'nama_kelas_id' => 3,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
            [
                'nisn' => 123123123,
                'nama' => 'Aisha Singgih',
                'nama_kelas_id' => 3,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
            [
                'nisn' => 123123123,
                'nama' => 'Aisyah Mutiara Maharani',
                'nama_kelas_id' => 3,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
            [
                'nisn' => 123123123,
                'nama' => 'Al Holi Liyatul Munawwaroh',
                'nama_kelas_id' => 3,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
            [
                'nisn' => 123123123,
                'nama' => 'Andara Ruri Firstanti',
                'nama_kelas_id' => 3,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
            [
                'nisn' => 123123123,
                'nama' => 'Angga Krisna Yudha',
                'nama_kelas_id' => 3,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
            [
                'nisn' => 123123123,
                'nama' => 'Aulia Anggy Andari',
                'nama_kelas_id' => 3,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Bagas Atha Nugroho',
                'nama_kelas_id' => 3,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Bagus Putra Kurniawan',
                'nama_kelas_id' => 3,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'carrya Nur Sidik',
                'nama_kelas_id' => 3,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Dian Asih Anggraini',
                'nama_kelas_id' => 3,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Dimas Wahyu Priam bodo',
                'nama_kelas_id' => 3,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Diyyaul Auliya',
                'nama_kelas_id' => 3,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Dwi Septia Anggari',
                'nama_kelas_id' => 3,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Elvira Damayanti',
                'nama_kelas_id' => 3,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
            [
                'nisn' => 123123123,
                'nama' => 'Erlinda Putri Maharani',
                'nama_kelas_id' => 3,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Erna Indriyani',
                'nama_kelas_id' => 3,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Fahdah Fathuna',
                'nama_kelas_id' => 3,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Fania Auradira Fahira',
                'nama_kelas_id' => 3,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Farell Marshal Asoka',
                'nama_kelas_id' => 3,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Fari Khatut Sani Rosidah',
                'nama_kelas_id' => 3,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Fina Putri Agustin',
                'nama_kelas_id' => 3,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Gading Sukma Nurlita Saputri',
                'nama_kelas_id' => 3,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Hana Alfiyanti',
                'nama_kelas_id' => 3,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Immanuel Yeremia Tielung',
                'nama_kelas_id' => 3,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Isti Qomatud Diyanah',
                'nama_kelas_id' => 3,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Khoironisak',
                'nama_kelas_id' => 3,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Mochammad Dandi Agus Nur Rochmad',
                'nama_kelas_id' => 3,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Oktavia Ramadhany Saputri',
                'nama_kelas_id' => 3,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Ramzy Agung Prambudi',
                'nama_kelas_id' => 3,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Shella Sapphira Tomy Tji',
                'nama_kelas_id' => 3,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Silvester Chievo Prabowo',
                'nama_kelas_id' => 3,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Theresia Queen Ericke',
                'nama_kelas_id' => 3,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             
        ];

        siswa::insert($kelas);
    }
}
