<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\siswa;

class XII_PSPT_1 extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $kelas = [
            [
                'nisn' => 123123123,
                'nama' => 'Adinda Adzani Rahmadanti',
                'nama_kelas_id' => 7,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
            [
                'nisn' => 123123123,
                'nama' => 'Aditya Kurniawan Syahputra',
                'nama_kelas_id' => 7,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
            [
                'nisn' => 123123123,
                'nama' => 'Ainun Evi Maisaroh',
                'nama_kelas_id' => 7,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
            [
                'nisn' => 123123123,
                'nama' => 'Alya Chelsea Ramadhani',
                'nama_kelas_id' => 7,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
            [
                'nisn' => 123123123,
                'nama' => 'Amanda Kayla Noer Farida',
                'nama_kelas_id' => 7,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
            [
                'nisn' => 123123123,
                'nama' => 'An Nisa` Amalia',
                'nama_kelas_id' => 7,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
            [
                'nisn' => 123123123,
                'nama' => 'Ananta Dhea Putri Pamudji',
                'nama_kelas_id' => 7,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
            [
                'nisn' => 123123123,
                'nama' => 'Ardhan Haqqi Wicaksono',
                'nama_kelas_id' => 7,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
            
            [
                'nisn' => 123123123,
                'nama' => 'Ardinda Dewi Nurjannah',
                'nama_kelas_id' => 7,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
            [
                'nisn' => 123123123,
                'nama' => 'Aurelia Inez Mega Sentosa',
                'nama_kelas_id' => 7,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
            [
                'nisn' => 123123123,
                'nama' => 'Aurell Shafvina',
                'nama_kelas_id' => 7,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
            [
                'nisn' => 123123123,
                'nama' => 'Baby Andrela Pepitha',
                'nama_kelas_id' => 7,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Baradhy Ariel Ghifri',
                'nama_kelas_id' => 7,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
            [
                'nisn' => 123123123,
                'nama' => 'Belinda Nabillah Oktavia',
                'nama_kelas_id' => 7,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Bella Setya Pratiwi',
                'nama_kelas_id' => 7,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Belva Arka Nuriyah',
                'nama_kelas_id' => 7,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Citra Dewi Alanjung',
                'nama_kelas_id' => 7,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Dandy Satriawan Wicaksono',
                'nama_kelas_id' => 7,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Devina Nirmala Putri',
                'nama_kelas_id' => 7,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Dhyansara Putri Laila Rizqi Wiratama',
                'nama_kelas_id' => 7,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Diah Virgianti Triono',
                'nama_kelas_id' => 7,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Dika Pratama Wahyu Syah Putra',
                'nama_kelas_id' => 7,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Dista Larasati',
                'nama_kelas_id' => 7,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Elrnira Rahma Qudsyah',
                'nama_kelas_id' => 7,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Ernawati',
                'nama_kelas_id' => 7,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Fara Aurelia Putri',
                'nama_kelas_id' => 7,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Fitri Dwi Novianti',
                'nama_kelas_id' => 7,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Fitria Ramadani',
                'nama_kelas_id' => 7,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Ghazian Fakhrusyakirin',
                'nama_kelas_id' => 7,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Gresimon Nenden Nadilla',
                'nama_kelas_id' => 7,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Grisheilla Advitiya',
                'nama_kelas_id' => 7,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Ica Velinda Diniartha',
                'nama_kelas_id' => 7,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Inayah Luthfiyah Nuraini',
                'nama_kelas_id' => 7,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Irfan Dzaki Rizqulloh',
                'nama_kelas_id' => 7,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             [
                'nisn' => 123123123,
                'nama' => 'Yohana Aprillia Putrining Nova',
                'nama_kelas_id' => 7,
                'users_id' => null,
                'alamat' => 'jalan-jalan',
                'jenis_kelamin' => 'perempuan',
            ],
             
        ];

        siswa::insert($kelas);
    }
}
